weather:
  api:
    key: ${WEATHER_API_KEY:64357b8936421af79c9c519ec0a532ed}
    url: ${WEATHER_URL:https://api.openweathermap.org/data/2.5/forecast}

logging:
  level:
    com.dushmantha: ${LOG_LEVEL:debug}
    root: ${ROOT_LOG_LEVEL:info}