weather:
  api:
    key: ${WEATHER_API_KEY:a1b2c3d4}
    url: ${WEATHER_URL:https://api.openweathermap.org/data/2.5/forecast}

logging:
  level:
    com.dushmantha: ${LOG_LEVEL:debug}
    root: ${ROOT_LOG_LEVEL:info}